# Generated by Django 4.2.4 on 2023-08-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('Discription', models.CharField(max_length=350)),
                ('Detailed_post', models.CharField(max_length=1500)),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
    ]
